In [1]:
import pandas as pd

In [2]:
datos=[["pursuit accident claim car driver exclude"],
["soak motorist company car driver risky"],
["company car driver tend travel farther"],
["job engineer disappear fall mechanical engineer car industry worst affect"],
["sign recession car industry"],
["brightest engineer moment car industry"],
["yugoslavia benefit direct investment automobile industry"],
["acreage expand emergence automobile industry"],
["automobile industry among hardest hit recession"],
["automobile industry largely male force"],
["component supplier automobile industry expand"],
["client industry manufacturer component automobile industry"]]

In [3]:
df = pd.DataFrame(datos,columns=['texto'])
df

                                                texto
0           pursuit accident claim car driver exclude
1              soak motorist company car driver risky
2              company car driver tend travel farther
3   job engineer disappear fall mechanical enginee...
4                         sign recession car industry
5              brightest engineer moment car industry
6   yugoslavia benefit direct investment automobil...
7        acreage expand emergence automobile industry
8     automobile industry among hardest hit recession
9              automobile industry largely male force
10      component supplier automobile industry expand
11  client industry manufacturer component automob...

In [4]:
from pmi import *
from preprocessing import *

In [5]:
string_list1,M=prepocessing.getTokens(df,0) 
M

70

In [6]:
setx = set(string_list1)
set1 = set()
for word_k in setx:
    set1.add((word_k,string_list1.count(word_k)))
list_words1 = pd.DataFrame(set1)
list_words1.columns = ['word','count']
list_words1 = list_words1.sort_values(['count'], ascending = False)
N = len(list_words1)
N

43

In [7]:
#convertimos el conjunto en un diccionario de conteos
diccionario_conteo_words={}
for a in set1:
    diccionario_conteo_words[a[0]]=a[1]
diccionario_conteo_words

{'male': 1,
 'benefit': 1,
 'risky': 1,
 'yugoslavia': 1,
 'expand': 2,
 'industry': 10,
 'company': 2,
 'affect': 1,
 'direct': 1,
 'farther': 1,
 'manufacturer': 1,
 'supplier': 1,
 'job': 1,
 'mechanical': 1,
 'accident': 1,
 'exclude': 1,
 'pursuit': 1,
 'force': 1,
 'emergence': 1,
 'recession': 2,
 'investment': 1,
 'worst': 1,
 'moment': 1,
 'automobile': 6,
 'sign': 1,
 'hardest': 1,
 'hit': 1,
 'disappear': 1,
 'component': 2,
 'client': 1,
 'brightest': 1,
 'claim': 1,
 'soak': 1,
 'among': 1,
 'motorist': 1,
 'acreage': 1,
 'car': 6,
 'driver': 3,
 'largely': 1,
 'tend': 1,
 'fall': 1,
 'travel': 1,
 'engineer': 3}

In [8]:
list_words1 = list_words1.assign(proba = list_words1['count']/M)
list_words1

            word  count     proba
5       industry     10  0.142857
23    automobile      6  0.085714
36           car      6  0.085714
37        driver      3  0.042857
42      engineer      3  0.042857
4         expand      2  0.028571
19     recession      2  0.028571
28     component      2  0.028571
6        company      2  0.028571
31         claim      1  0.014286
25       hardest      1  0.014286
26           hit      1  0.014286
27     disappear      1  0.014286
29        client      1  0.014286
30     brightest      1  0.014286
32          soak      1  0.014286
33         among      1  0.014286
24          sign      1  0.014286
35       acreage      1  0.014286
41        travel      1  0.014286
40          fall      1  0.014286
38       largely      1  0.014286
39          tend      1  0.014286
34      motorist      1  0.014286
0           male      1  0.014286
22        moment      1  0.014286
1        benefit      1  0.014286
2          risky      1  0.014286
3     yugoslavia      1  0.014286
7         affect      1  0.014286
8         direct      1  0.014286
9        farther      1  0.014286
10  manufacturer      1  0.014286
11      supplier      1  0.014286
12           job      1  0.014286
13    mechanical      1  0.014286
14      accident      1  0.014286
15       exclude      1  0.014286
16       pursuit      1  0.014286
17         force      1  0.014286
18     emergence      1  0.014286
20    investment      1  0.014286
21         worst      1  0.014286

In [9]:
#creamos una lista para el vocabulario
vocabulario=list_words1['word'].to_list()
vocabulario

['industry',
 'automobile',
 'car',
 'driver',
 'engineer',
 'expand',
 'recession',
 'component',
 'company',
 'claim',
 'hardest',
 'hit',
 'disappear',
 'client',
 'brightest',
 'soak',
 'among',
 'sign',
 'acreage',
 'travel',
 'fall',
 'largely',
 'tend',
 'motorist',
 'male',
 'moment',
 'benefit',
 'risky',
 'yugoslavia',
 'affect',
 'direct',
 'farther',
 'manufacturer',
 'supplier',
 'job',
 'mechanical',
 'accident',
 'exclude',
 'pursuit',
 'force',
 'emergence',
 'investment',
 'worst']

In [10]:
#a partir del vocabulario combinamos para generar tuplas
set_temp=set()
for a in vocabulario[:]:
    for b in vocabulario[:]:
        t=(a,b)
        if(t not in set_temp):
            tupla=(b,a)
            if(tupla not in set_temp):#set_temp.add(t)
                set_temp.add(t)
len(set_temp)

946

In [11]:
#setear sus valores a 0 y crear diccionario para más facil acceso
diccionario_conteo_word_word1={}
for e in set_temp:
  diccionario_conteo_word_word1[e]=0

In [12]:
df['texto2']=df['texto']
df

,texto,texto2
0,pursuit accident claim car driver exclude,pursuit accident claim car driver exclude
1,soak motorist company car driver risky,soak motorist company car driver risky
2,company car driver tend travel farther,company car driver tend travel farther
3,job engineer disappear fall mechanical enginee...,job engineer disappear fall mechanical enginee...
4,sign recession car industry,sign recession car industry
5,brightest engineer moment car industry,brightest engineer moment car industry
6,yugoslavia benefit direct investment automobil...,yugoslavia benefit direct investment automobil...
7,acreage expand emergence automobile industry,acreage expand emergence automobile industry
8,automobile industry among hardest hit recession,automobile industry among hardest hit recession
9,automobile industry largely male force,automobile industry largely male force
10,component supplier automobile industry expand,component supplier automobile industry expand
11,client industry manufacturer component automob...,client industry manufacturer component automob...

Fórmula para el calculo
$PMI(w_i , w_j) = log_2 \frac{ C(w_i , w_j) * M }{ C(w_i)*C(w_j) }$

In [13]:
#Ahora vamos a ejecutar el calculo del pmi para cada palabra
import time
import numpy as np
start = time.time()
diccionario_conteo_word_word=pmi.obtener_dicc_conteo(11, df,diccionario_conteo_word_word1)
print("Se obtuvo el conteo de word a word")
diccionario_PMI_word_word=pmi.obtener_dicc_PMI(diccionario_conteo_word_word,diccionario_conteo_words,M)
print("PMI obtenido")
end = time.time()
print(end-start)

Se obtuvo el conteo de word a word
PMI obtenido
0.0011258125305175781

In [14]:
dfdicc1_3 = pd.DataFrame([[key, diccionario_PMI_word_word[key]] for key in diccionario_PMI_word_word.keys()], columns=['Tupla', 'PMI'])
dfdicc1_3 =dfdicc1_3.sort_values('PMI', ascending=False)
dfdicc1_3

                       Tupla       PMI
46        (disappear, worst)  6.129283
38      (affect, mechanical)  6.129283
96            (travel, tend)  6.129283
25      (acreage, emergence)  6.129283
137      (mechanical, worst)  6.129283
..                       ...       ...
115    (industry, component)  2.807355
120  (automobile, recession)  2.544321
9           (car, recession)  2.544321
111     (industry, engineer)  2.222392
73           (industry, car)  1.807355

[149 rows x 2 columns]

Fórmula para el calculo
$SIM(w_i , w_j) = \frac{ fB(w_i) }{ B_1 } + \frac{ fB(w_j) }{ B_2 }$

In [15]:
# calculamos para cada tupla mostrada anteriormente, cual es su valor de similitud. Para poder hacer esto hay que cerciorarte de que ya tengamos 
# # un diccionario con las tuplas con pmi
dfdicc1_3['similitudPMI']=""
temp=dfdicc1_3.copy()
for index, string in temp.iterrows():
    tup=tuple(string[0])
    dfdicc1_3.at[index,'similitudPMI']=pmi.similarity_PMI(tup[0],tup[1],diccionario_conteo_words[tup[0]],diccionario_conteo_words[tup[1]],N,3,0.7)
    #print(string[0])
dfdicc1_3

                       Tupla       PMI similitudPMI
46        (disappear, worst)  6.129283   270.389083
38      (affect, mechanical)  6.129283   270.389083
96            (travel, tend)  6.129283   201.433299
25      (acreage, emergence)  6.129283   100.799516
137      (mechanical, worst)  6.129283   270.389083
..                       ...       ...          ...
115    (industry, component)  2.807355    35.763872
120  (automobile, recession)  2.544321    44.714952
9           (car, recession)  2.544321    13.748812
111     (industry, engineer)  2.222392    44.179735
73           (industry, car)  1.807355    24.446577

[149 rows x 3 columns]

In [16]:
pmi.similarity_PMI('automobile','car',diccionario_conteo_words['car'],diccionario_conteo_words['automobile'],N,3,0.7)

2.785789110227461

In [17]:
diccionario_conteo_words['car']

6

In [18]:
dfdicc1_3.to_pickle('validacionPMI.pickle')

In [19]:
dfdicc1_3.to_csv('validacionPMI.csv')